version: v1beta11
deployments:
  - name: user-service
    kubectl:
      manifests:
        - k8s/deployment.yaml
        - k8s/service.yaml

dev:
  ports:
    - labelSelector:
        app: user-service
      forward:
        - port: 8080
  sync:
    - labelSelector:
        app: user-service
      localSubPath: .
      containerPath: /app
      uploadExcludePaths:
        - .git/
        - target/
        - .idea/
        - .vscode/
  logs:
    - labelSelector:
        app: user-service